In [54]:
import numpy as np
import pandas as pd

In [55]:
x = [1,2,3,4,5]
nx = np.array(x)
print(nx)

[1 2 3 4 5]


In [56]:
print(nx.shape)

(5,)


In [57]:
ny = np.array([[1,2,3],[4,5,6]])
print(ny)

[[1 2 3]
 [4 5 6]]


In [58]:
print(ny.shape)

(2, 3)


In [59]:
one = np.arange(1,100,0.2)
one

array([ 1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,  2.6,  2.8,  3. ,
        3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,
        5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,
        7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,
        9.8, 10. , 10.2, 10.4, 10.6, 10.8, 11. , 11.2, 11.4, 11.6, 11.8,
       12. , 12.2, 12.4, 12.6, 12.8, 13. , 13.2, 13.4, 13.6, 13.8, 14. ,
       14.2, 14.4, 14.6, 14.8, 15. , 15.2, 15.4, 15.6, 15.8, 16. , 16.2,
       16.4, 16.6, 16.8, 17. , 17.2, 17.4, 17.6, 17.8, 18. , 18.2, 18.4,
       18.6, 18.8, 19. , 19.2, 19.4, 19.6, 19.8, 20. , 20.2, 20.4, 20.6,
       20.8, 21. , 21.2, 21.4, 21.6, 21.8, 22. , 22.2, 22.4, 22.6, 22.8,
       23. , 23.2, 23.4, 23.6, 23.8, 24. , 24.2, 24.4, 24.6, 24.8, 25. ,
       25.2, 25.4, 25.6, 25.8, 26. , 26.2, 26.4, 26.6, 26.8, 27. , 27.2,
       27.4, 27.6, 27.8, 28. , 28.2, 28.4, 28.6, 28.8, 29. , 29.2, 29.4,
       29.6, 29.8, 30. , 30.2, 30.4, 30.6, 30.8, 31

In [60]:
print(one.size)

495


In [61]:
two = np.linspace(0,100,200)
two

array([  0.        ,   0.50251256,   1.00502513,   1.50753769,
         2.01005025,   2.51256281,   3.01507538,   3.51758794,
         4.0201005 ,   4.52261307,   5.02512563,   5.52763819,
         6.03015075,   6.53266332,   7.03517588,   7.53768844,
         8.04020101,   8.54271357,   9.04522613,   9.54773869,
        10.05025126,  10.55276382,  11.05527638,  11.55778894,
        12.06030151,  12.56281407,  13.06532663,  13.5678392 ,
        14.07035176,  14.57286432,  15.07537688,  15.57788945,
        16.08040201,  16.58291457,  17.08542714,  17.5879397 ,
        18.09045226,  18.59296482,  19.09547739,  19.59798995,
        20.10050251,  20.60301508,  21.10552764,  21.6080402 ,
        22.11055276,  22.61306533,  23.11557789,  23.61809045,
        24.12060302,  24.62311558,  25.12562814,  25.6281407 ,
        26.13065327,  26.63316583,  27.13567839,  27.63819095,
        28.14070352,  28.64321608,  29.14572864,  29.64824121,
        30.15075377,  30.65326633,  31.15577889,  31.65

In [62]:
n3 = np.random.rand(100)
n3

array([3.28525060e-01, 6.94957773e-01, 1.63219208e-01, 2.68287857e-01,
       2.02081608e-01, 9.78442173e-01, 1.24403596e-01, 8.05344645e-01,
       7.64727013e-01, 4.83375656e-01, 5.11966719e-01, 3.50703801e-01,
       1.03130775e-01, 9.26556045e-01, 2.62096185e-01, 6.86413709e-01,
       1.80860755e-01, 9.40866062e-01, 4.94575225e-01, 1.00390652e-01,
       2.22947607e-02, 2.39899667e-01, 8.60124982e-01, 3.84737662e-01,
       5.03436395e-01, 2.81470348e-01, 4.39880574e-01, 4.56141272e-01,
       2.92238518e-01, 2.40380839e-02, 6.35539752e-01, 1.49402989e-01,
       5.41582783e-01, 2.48507828e-01, 7.26065030e-01, 2.32344146e-01,
       5.05059006e-01, 2.73761121e-01, 1.37908886e-01, 9.97628118e-01,
       8.09570456e-01, 3.93783855e-01, 8.36100964e-01, 7.46289640e-01,
       9.35744399e-02, 4.68244962e-02, 6.03115453e-01, 3.55752036e-01,
       4.92248707e-01, 8.50695547e-02, 6.45777611e-01, 9.80358337e-01,
       1.36953650e-01, 6.65780164e-01, 7.31917509e-01, 3.98014733e-01,
      

In [63]:
n4 = np.random.randint(1,10,100)
n4

array([6, 1, 7, 2, 9, 1, 3, 3, 5, 7, 6, 4, 9, 4, 3, 1, 8, 9, 9, 2, 2, 8,
       6, 4, 5, 8, 8, 6, 9, 9, 4, 2, 7, 9, 3, 8, 8, 6, 5, 5, 8, 1, 3, 5,
       7, 5, 1, 4, 8, 7, 2, 3, 4, 9, 3, 3, 1, 6, 7, 4, 2, 8, 8, 4, 4, 7,
       7, 8, 9, 6, 1, 8, 6, 7, 7, 1, 4, 2, 5, 2, 6, 8, 1, 9, 2, 5, 5, 6,
       1, 1, 6, 3, 4, 5, 8, 7, 2, 5, 8, 2])

In [64]:
n4.reshape((10,10))

array([[6, 1, 7, 2, 9, 1, 3, 3, 5, 7],
       [6, 4, 9, 4, 3, 1, 8, 9, 9, 2],
       [2, 8, 6, 4, 5, 8, 8, 6, 9, 9],
       [4, 2, 7, 9, 3, 8, 8, 6, 5, 5],
       [8, 1, 3, 5, 7, 5, 1, 4, 8, 7],
       [2, 3, 4, 9, 3, 3, 1, 6, 7, 4],
       [2, 8, 8, 4, 4, 7, 7, 8, 9, 6],
       [1, 8, 6, 7, 7, 1, 4, 2, 5, 2],
       [6, 8, 1, 9, 2, 5, 5, 6, 1, 1],
       [6, 3, 4, 5, 8, 7, 2, 5, 8, 2]])

In [65]:
n5 = n4.reshape((25,4))
n5

array([[6, 1, 7, 2],
       [9, 1, 3, 3],
       [5, 7, 6, 4],
       [9, 4, 3, 1],
       [8, 9, 9, 2],
       [2, 8, 6, 4],
       [5, 8, 8, 6],
       [9, 9, 4, 2],
       [7, 9, 3, 8],
       [8, 6, 5, 5],
       [8, 1, 3, 5],
       [7, 5, 1, 4],
       [8, 7, 2, 3],
       [4, 9, 3, 3],
       [1, 6, 7, 4],
       [2, 8, 8, 4],
       [4, 7, 7, 8],
       [9, 6, 1, 8],
       [6, 7, 7, 1],
       [4, 2, 5, 2],
       [6, 8, 1, 9],
       [2, 5, 5, 6],
       [1, 1, 6, 3],
       [4, 5, 8, 7],
       [2, 5, 8, 2]])

In [66]:
n1 = np.random.randint(1,10,(5,5))
n2 = np.random.randint(1,10,(5,5))

In [67]:
n1 + n2

array([[ 2, 13, 13, 16, 12],
       [ 9,  4,  8, 16,  5],
       [15, 15,  2, 13, 14],
       [10,  9, 12,  7,  4],
       [15,  6,  7, 11, 11]])

In [68]:
n1 - n2

array([[ 0, -3,  3, -2,  4],
       [-3, -2,  0,  0,  1],
       [-1, -3,  0, -5,  0],
       [-2,  7,  2,  5, -2],
       [ 3,  2, -1, -3, -1]])

In [69]:
n1 / n2

array([[1.        , 0.625     , 1.6       , 0.77777778, 2.        ],
       [0.5       , 0.33333333, 1.        , 1.        , 1.5       ],
       [0.875     , 0.66666667, 1.        , 0.44444444, 1.        ],
       [0.66666667, 8.        , 1.4       , 6.        , 0.33333333],
       [1.5       , 2.        , 0.75      , 0.57142857, 0.83333333]])

In [70]:
n1 ** n2

array([[       1,   390625,    32768, 40353607,     4096],
       [     729,        1,      256, 16777216,        9],
       [ 5764801, 10077696,        1,   262144,   823543],
       [    4096,        8,    16807,        6,        1],
       [  531441,       16,       81,    16384,    15625]])

In [71]:
n1 ** 4

array([[   1,  625, 4096, 2401, 4096],
       [  81,    1,  256, 4096,   81],
       [2401, 1296,    1,  256, 2401],
       [ 256, 4096, 2401, 1296,    1],
       [6561,  256,   81,  256,  625]], dtype=int32)

In [72]:
n1 + 10

array([[11, 15, 18, 17, 18],
       [13, 11, 14, 18, 13],
       [17, 16, 11, 14, 17],
       [14, 18, 17, 16, 11],
       [19, 14, 13, 14, 15]])

In [73]:
n1.dot(n2)

array([[185, 118, 100, 184, 139],
       [107,  77,  75, 100,  84],
       [117, 101, 108, 173, 101],
       [150, 127,  93, 176, 105],
       [111, 125, 104, 179, 107]])

In [74]:
n1 * n2

array([[ 1, 40, 40, 63, 32],
       [18,  3, 16, 64,  6],
       [56, 54,  1, 36, 49],
       [24,  8, 35,  6,  3],
       [54,  8, 12, 28, 30]])

In [75]:
n1 , n2

(array([[1, 5, 8, 7, 8],
        [3, 1, 4, 8, 3],
        [7, 6, 1, 4, 7],
        [4, 8, 7, 6, 1],
        [9, 4, 3, 4, 5]]),
 array([[1, 8, 5, 9, 4],
        [6, 3, 4, 8, 2],
        [8, 9, 1, 9, 7],
        [6, 1, 5, 1, 3],
        [6, 2, 4, 7, 6]]))

In [76]:
n1 % n2

array([[0, 5, 3, 7, 0],
       [3, 1, 0, 0, 1],
       [7, 6, 0, 4, 0],
       [4, 0, 2, 0, 1],
       [3, 0, 3, 4, 5]])

In [77]:
n6 = np.random.randint(1,10,10)
n6

array([4, 9, 8, 1, 7, 3, 6, 3, 2, 4])

In [78]:
n6[0]

4

In [79]:
n6[1]

9

In [80]:
n6[-1]

4

In [81]:
n6[:5]

array([4, 9, 8, 1, 7])

In [82]:
n6[5:]

array([3, 6, 3, 2, 4])

In [83]:
# flatten a n dimensional matrix to 1 dimensional matrix
n5.flatten()

array([6, 1, 7, 2, 9, 1, 3, 3, 5, 7, 6, 4, 9, 4, 3, 1, 8, 9, 9, 2, 2, 8,
       6, 4, 5, 8, 8, 6, 9, 9, 4, 2, 7, 9, 3, 8, 8, 6, 5, 5, 8, 1, 3, 5,
       7, 5, 1, 4, 8, 7, 2, 3, 4, 9, 3, 3, 1, 6, 7, 4, 2, 8, 8, 4, 4, 7,
       7, 8, 9, 6, 1, 8, 6, 7, 7, 1, 4, 2, 5, 2, 6, 8, 1, 9, 2, 5, 5, 6,
       1, 1, 6, 3, 4, 5, 8, 7, 2, 5, 8, 2])

In [84]:
# flatten a n dimensional matrix to 1 dimensional matrix
n5.ravel()

array([6, 1, 7, 2, 9, 1, 3, 3, 5, 7, 6, 4, 9, 4, 3, 1, 8, 9, 9, 2, 2, 8,
       6, 4, 5, 8, 8, 6, 9, 9, 4, 2, 7, 9, 3, 8, 8, 6, 5, 5, 8, 1, 3, 5,
       7, 5, 1, 4, 8, 7, 2, 3, 4, 9, 3, 3, 1, 6, 7, 4, 2, 8, 8, 4, 4, 7,
       7, 8, 9, 6, 1, 8, 6, 7, 7, 1, 4, 2, 5, 2, 6, 8, 1, 9, 2, 5, 5, 6,
       1, 1, 6, 3, 4, 5, 8, 7, 2, 5, 8, 2])

In [85]:
x = np.random.randint(1,10,(5,5))

In [86]:
n7 = np.random.randint(1,10,(3,4))
n7

array([[3, 6, 8, 6],
       [6, 1, 8, 1],
       [1, 6, 7, 9]])

In [87]:
print(x[0])

[5 8 1 4 9]


In [88]:
print(x[-1])

[6 6 2 8 7]


In [89]:
print(x[:2,2:])

[[1 4 9]
 [2 9 7]]


In [90]:
print(x[:,0])

[5 6 1 1 6]


In [91]:
x = np.random.randint(1,10,(5,5))

In [92]:
x.transpose() # transpose the matrix, row to col and col to row

array([[3, 2, 4, 1, 6],
       [5, 6, 6, 5, 7],
       [9, 3, 1, 8, 8],
       [5, 9, 2, 5, 8],
       [3, 5, 5, 3, 5]])

In [93]:
x.T # transpose the matrix, row to column and column to row

array([[3, 2, 4, 1, 6],
       [5, 6, 6, 5, 7],
       [9, 3, 1, 8, 8],
       [5, 9, 2, 5, 8],
       [3, 5, 5, 3, 5]])

In [94]:
n6

array([4, 9, 8, 1, 7, 3, 6, 3, 2, 4])

In [95]:
n6.max()

9

In [96]:
n6.mean()

4.7

In [97]:
n6.sum()

47

In [98]:
n5.sum() # sum of all values

512

In [99]:
n5.sum(axis = 0) # sum all values in each column

array([136, 144, 126, 106])

In [100]:
n5.sum(axis = 1) # sum all values in each row

array([16, 16, 22, 17, 28, 20, 27, 24, 27, 24, 17, 17, 20, 19, 18, 22, 26,
       24, 21, 13, 24, 18, 11, 24, 17])

In [101]:
print(n6, n6.max(), "found at index", n6.argmax())
print(n6, n6.max(), "found at index", n6.argmin())

[4 9 8 1 7 3 6 3 2 4] 9 found at index 1
[4 9 8 1 7 3 6 3 2 4] 9 found at index 3


In [102]:
n6.argmax() # the index of the max value

1

In [103]:
a = np.random.randint(1,100,(3,2))
b = np.random.randint(1,100,(3,2))
c = np.random.randint(1,100,(2,3))
print(a)
print(b)
print(c)

[[40 32]
 [15 86]
 [31 10]]
[[41 33]
 [11 56]
 [83 93]]
[[95 44 54]
 [73 39 59]]


In [104]:
np.hstack((a,b)) # horizontal stack

array([[40, 32, 41, 33],
       [15, 86, 11, 56],
       [31, 10, 83, 93]])

In [105]:
np.vstack((a,b)) #vertical stack

array([[40, 32],
       [15, 86],
       [31, 10],
       [41, 33],
       [11, 56],
       [83, 93]])

In [106]:
np.vstack((a, c.T))

array([[40, 32],
       [15, 86],
       [31, 10],
       [95, 73],
       [44, 39],
       [54, 59]])

In [107]:
m = np.array([1,2,3,4,5,6,7,8,3,4,5,6,7,8,1,2,3,4,5,1,2,3,4,6,7,8,9,9,4,5,4,5,2,3,44,4,43,2,2,11,12,34,5,3,3,4,1,2,3,4,5,67])

In [108]:
# boolean filter
m > 5

array([False, False, False, False, False,  True,  True,  True, False,
       False, False,  True,  True,  True, False, False, False, False,
       False, False, False, False, False,  True,  True,  True,  True,
        True, False, False, False, False, False, False,  True, False,
        True, False, False,  True,  True,  True, False, False, False,
       False, False, False, False, False, False,  True])

In [109]:
m[m > 5]

array([ 6,  7,  8,  6,  7,  8,  6,  7,  8,  9,  9, 44, 43, 11, 12, 34, 67])

In [110]:
m[m != 2]

array([ 1,  3,  4,  5,  6,  7,  8,  3,  4,  5,  6,  7,  8,  1,  3,  4,  5,
        1,  3,  4,  6,  7,  8,  9,  9,  4,  5,  4,  5,  3, 44,  4, 43, 11,
       12, 34,  5,  3,  3,  4,  1,  3,  4,  5, 67])

In [111]:
# in range of 2 to 8
m[(m > 2) & (m < 8)]

array([3, 4, 5, 6, 7, 3, 4, 5, 6, 7, 3, 4, 5, 3, 4, 6, 7, 4, 5, 4, 5, 3,
       4, 5, 3, 3, 4, 3, 4, 5])

In [112]:
# user created numpy matrix
mat = [ ]
for i in range(10):
    mat.append(int(input('enter value')))
mat = np.array(mat)

In [113]:
print(mat, mat.shape)

[1 2 3 4 5 6 7 8 9 3] (10,)


In [114]:
# user created numpy matrix
mat = []
for i in range(2):
    smat = []
    for j in range(3):
        smat.append(int(input('enter value')))
    mat.append(smat)
mat = np.array(mat)
print(mat, mat.shape)

[[4 5 6]
 [7 3 4]] (2, 3)
